### ISSUE TITLE
关于爬虫的问题

### ISSUE THREAD

**Issue by TianMonki** [yejue/spider2dataVisualization#1]
所以如何在项目中实现爬虫爬取新数据而不是使用所给的数据呢？

**Comment by yejue** [comment]
> 所以如何在项目中实现爬虫爬取新数据而不是使用所给的数据呢？

这个项目本身是爬虫与展示两个部分兼备，爬虫部分在 spider 里面，因为某些原因没有写到文档里，需要看代码。为爬虫配备了 django 的 command。
